version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "9.4.x"
    schedule:
      interval: "daily"
    ignore:
      # Do not upgrade major versions of dependencies
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
      # Restrict updates in this branch to jetty in the 9.4.x space
      - dependency-name: "org.jboss.weld.servlet:*"
        update-types: [ "version-update:semver-minor" ]
      - dependency-name: "javax.websocket:*"
      - dependency-name: "javax.servlet:*"
      - dependency-name: "javax.servlet.jsp:*"

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "10.0.x"
    schedule:
      interval: "daily"
    ignore:
      # Do not upgrade major versions of dependencies
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
      # Restrict updates in this branch to jetty in the 10.x.x space
      - dependency-name: "org.jboss.weld.servlet:*"
        update-types: [ "version-update:semver-minor" ]
      - dependency-name: "jakarta.websocket:*"
      - dependency-name: "jakarta.servlet:*"
      - dependency-name: "jakarta.servlet.jsp:*"

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "11.0.x"
    schedule:
      interval: "daily"
    ignore:
      # Do not upgrade major versions of dependencies
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
      # Restrict updates in this branch to jetty in the 11.x.x space
      - dependency-name: "org.jboss.weld.servlet:*"
        update-types: [ "version-update:semver-minor" ]
      - dependency-name: "org.glassfish.jersey:*"
        update-types: [ "version-update:semver-minor" ]
      - dependency-name: "org.glassfish.jersey.containers:*"
        update-types: [ "version-update:semver-minor" ]
      - dependency-name: "org.glassfish.jersey.inject:*"
        update-types: [ "version-update:semver-minor" ]
      - dependency-name: "org.glassfish.jersey.media:*"
        update-types: [ "version-update:semver-minor" ]
      - dependency-name: "jakarta.websocket:*"
      - dependency-name: "jakarta.servlet:*"
      - dependency-name: "jakarta.servlet.jsp:*"

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "12.0.x"
    schedule:
      interval: "daily"
    ignore:
      # Do not upgrade major versions of dependencies
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
      # Restrict updates in this branch to jetty in the 12.x.x space
      - dependency-name: "org.jboss.weld.servlet:*"
        update-types: [ "version-update:semver-minor" ]
      - dependency-name: "jakarta.websocket:*"
      - dependency-name: "jakarta.servlet:*"
      - dependency-name: "jakarta.servlet.jsp:*"
