# --------------------------------------- 
# Module: logging-log4j2
# Configures Jetty logging to use log4j version 2.
# SLF4J is used as the core logging mechanism.
# --------------------------------------- 
--modules=logging-log4j2


