<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.jetty.examples.embedded</groupId>
    <artifactId>ee10-webapp-isolated-logging</artifactId>
    <version>12.1.x</version>
  </parent>
  <artifactId>ee10-server</artifactId>
  <version>12.1.x</version>
  <packaging>jar</packaging>
  <name>Jetty Examples :: Jetty 12.1.x :: Embedded :: EE10 WebApp Isolated Logging :: Server</name>

  <dependencies>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-server</artifactId>
      <version>${jetty.version}</version>
    </dependency>

    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-slf4j-impl</artifactId>
      <version>${jetty.version}</version>
    </dependency>

    <dependency>
      <groupId>org.eclipse.jetty.ee10</groupId>
      <artifactId>jetty-ee10-annotations</artifactId>
      <version>${jetty.version}</version>
    </dependency>

    <dependency>
      <groupId>org.eclipse.jetty.ee10</groupId>
      <artifactId>jetty-ee10-webapp</artifactId>
      <version>${jetty.version}</version>
    </dependency>

    <dependency>
      <groupId>org.eclipse.jetty.examples.embedded</groupId>
      <artifactId>ee10-webapp-using-logback</artifactId>
      <version>${project.version}</version>
      <type>war</type>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.8.1</version>
        <executions>
          <execution>
            <id>copy-wars</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <includeArtifactIds>ee10-webapp-using-logback</includeArtifactIds>
              <includeScope>runtime</includeScope>
              <includeTypes>war</includeTypes>
              <overWriteSnapshots>true</overWriteSnapshots>
              <overWriteReleases>true</overWriteReleases>
              <stripVersion>true</stripVersion>
              <outputDirectory>${project.build.directory}/webapps</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
